"use client";
import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'hi' | 'es' | 'fr' | 'de' | 'it' | 'pt' | 'zh' | 'ja' | 'ru' | 'ar';

interface Translations {
    [key: string]: {
        [key: string]: string;
    };
}

const translations: Translations = {
    en: {
        'nav.home': 'Home',
        'nav.products': 'Products',
        'nav.about': 'About',
        'nav.contact': 'Contact',
        'nav.login': 'Login',
        'nav.logout': 'Logout',
        'hero.title': 'Premium Olive Oil',
        'hero.subtitle': 'Experience the purity of nature with our cold-pressed olive oil.',
        'hero.cta': 'Shop Now',
        'footer.text': '© 2026 Green Gold. All rights reserved.',
        'cart.title': 'Your Shopping Cart',
        'cart.checkout': 'Proceed to Checkout',
        'common.loading': 'Loading...',
        'home.hero.title': 'Pure Gold from Nature',
        'home.hero.subtitle': 'Experience the richness of premium, cold-pressed Green Gold (Olive Oil). Sourced globally, delivered locally.',
        'home.why': 'Why Choose Green Gold?',
        'home.featured': 'Featured Collections',
        'home.about.title': 'The Essence of Purity',
        'home.testimonials': 'What Our Customers Say',
        'product.organic.title': 'Organic Extra Virgin Olive Oil',
        'product.cold.title': 'Cold Pressed Olive Oil',
        'product.garlic.title': 'Infused Garlic Olive Oil',
        'product.skin.title': 'Skin Care Olive Oil',
        'category.premium': 'Premium',
        'category.classic': 'Classic',
        'category.infused': 'Infused',
        'category.beauty': 'Beauty',
        'footer.desc': 'Bringing the purest, cold-pressed olive oil from organic farms directly to your kitchen. Experience the gold standard of health.',
        'footer.quick': 'Quick Links',
        'footer.customer': 'Customer Care',
        'footer.stay': 'Stay Updated',
        'footer.sub': 'Subscribe for exclusive offers and health tips.',
        'footer.join': 'Join',
        'feature.pure.title': '100% Pure',
        'feature.pure.desc': 'Virgin & organic, directly from the farm.',
        'feature.cold.title': 'Cold Pressed',
        'feature.cold.desc': 'Retains all natural nutrients and flavor.',
        'feature.chem.title': 'No Chemicals',
        'feature.chem.desc': 'Zero additives, preservatives, or artificial colors.',
        'feature.lab.title': 'Lab Tested',
        'feature.lab.desc': 'Certified for quality and purity.',
        'about.text': 'Our journey began with a simple mission: to bring the authentic taste and health benefits of Mediterranean olive oil to your table. Every bottle of Green Gold is a promise of quality, harvested from ancient groves and cold-pressed to preserve its natural goodness.',
        'testimonial.quote': 'Absolutely the best olive oil I\'ve ever tasted. The flavor is rich and authentic. I use it for everything from cooking to salads!',
        'about.cta': 'Read Our Story',
        'footer.shipping': 'Shipping Policy',
        'footer.returns': 'Returns & Refunds',
        'footer.privacy': 'Privacy Policy',
        'footer.terms': 'Terms of Service',
        'home.cert.title': 'Certified for Excellence',
        'cert.fssai': 'FSSAI Certified',
        'cert.organic': '100% Organic',
        'cert.iso': 'ISO 9001:2015',
        'shop.title': 'Our Collection',
        'shop.filters.categories': 'Categories',
        'shop.filters.price': 'Price Range',
        'shop.filters.size': 'Size',
        'shop.filters.price_text': 'Price',
        'category.all': 'All',
        'category.bestsellers': 'Best Sellers',
        'shop.showing': 'Showing',
        'shop.results': 'results',
        'shop.sort.pop': 'Sort by Popularity',
        'shop.sort.low': 'Price: Low to High',
        'shop.sort.high': 'Price: High to Low',
        'shop.no_products': 'No products found in this category.',
        'about.hero.title': 'Cultivating Traditions',
        'about.hero.subtitle': 'Since 1985, Olive Oil has been dedicated to producing the world\'s finest organic olive oil, preserving ancient methods while embracing modern sustainability.',
        'about.story.title': 'Rooted in Nature',
        'about.story.p1': 'It all started in the sun-drenched hills of Andalusia, Spain. Our founders, the Garcia family, believed that true quality comes from a deep respect for the land. For generations, we have tended to our olive groves without the use of harsh chemicals or pesticides.',
        'about.story.p2': 'Every bottle of Olive Oil tells a story of patience and passion. We harvest our olives at the peak of ripeness and cold-press them within hours to capture the vibrant flavors and potent antioxidants that nature intended.',
        'about.story.p3': 'Today, we are proud to share this liquid gold with families around the world, bringing a touch of Mediterranean health and luxury to your kitchen.',
        'about.stat.exp': 'Years Experience',
        'about.stat.acres': 'Acres of Groves',
        'about.stat.cust': 'Happy Customers',
        'about.stat.cert': 'Organic Certified',
        'about.values.title': 'Our Core Values',
        'value.sus.title': 'Sustainability',
        'value.sus.desc': 'We practice regenerative agriculture to ensure our land thrives for future generations.',
        'value.int.title': 'Integrity',
        'value.int.desc': 'Transparency is key. We guarantee unmatched purity from tree to bottle.',
        'value.com.title': 'Community',
        'value.com.desc': 'We support fair trade and empower local farmers in every region we operate.',
        'value.exc.title': 'Excellence',
        'value.exc.desc': 'Award-winning quality recognized by top chefs and health experts worldwide.',
        'benefits.title': 'The Golden Elixir of Health',
        'benefits.subtitle': 'Discover the science-backed benefits of Olive Oil',
        'benefits.heart.title': 'Heart Health',
        'benefits.heart.desc': 'Olive oil is rich in monounsaturated fats, which help lower bad cholesterol (LDL) and maintain healthy blood pressure levels. It\'s a cornerstone of the heart-healthy Mediterranean diet.',
        'benefits.weight.title': 'Weight Management',
        'benefits.weight.desc': 'Despite being a fat, olive oil can aid in weight loss. The healthy fats increase satiety, helping you feel full longer and reducing the urge to snack on unhealthy foods.',
        'benefits.skin.title': 'Skin & Hair Care',
        'benefits.skin.desc': 'Rich in Vitamin E and antioxidants, olive oil nourishes the skin, combats aging signs, and strengthens hair from root to tip. It\'s a natural moisturizer and protector.',
        'benefits.anti.title': 'Anti-Inflammatory',
        'benefits.anti.desc': 'Contains oleocanthal, a compound with potent anti-inflammatory properties similar to ibuprofen. It helps reduce inflammation in the body and supports overall immunity.',
        'benefits.science.title': 'Backed by Science',
        'benefits.science.text': 'Olive Oil consists mainly of oleic acid (up to 83%), with smaller amounts of other fatty acids including linoleic acid (up to 21%) and palmitic acid (up to 20%). Studies showed that replacing saturated fats with unsaturated fats like those found in olive oil reduces the risk of cardiovascular events.',
        'blog.title': 'Olive Blog & Recipes',
        'blog.subtitle': 'Tips, tricks, and tales from the world of healthy living.',
        'blog.post1.title': '5 Easy Salad Dressings with Olive Oil',
        'blog.post1.excerpt': 'Elevate your salads with these simple, healthy, and delicious homemade dressings.',
        'blog.post2.title': 'Can You Fry with Extra Virgin Olive Oil?',
        'blog.post2.excerpt': 'Debunking the myths around smoke points and cooking with premium olive oil.',
        'blog.post3.title': 'The Ultimate Guide to Mediterranean Diet',
        'blog.post3.excerpt': 'How to incorporate liquid gold into your daily diet for maximum health benefits.',
        'blog.category.recipes': 'Recipes',
        'blog.category.cooking': 'Cooking Tips',
        'blog.category.health': 'Health',
        'blog.readmore': 'Read More',
        'blog.back': 'Back to Blog',
        'blog.share': 'Share this article',
        'blog.recent': 'Recent Posts',
        'blog.categories': 'Categories',
        'contact.hero.title': 'Get in Touch',
        'contact.hero.subtitle': 'Have questions about our products or partnership opportunities? We\'d love to hear from you.',
        'contact.call.title': 'Call Us',
        'contact.call.hours': 'Mon-Fri, 9am - 6pm EST',
        'contact.email.title': 'Email Us',
        'contact.visit.title': 'Visit Us',
        'contact.follow': 'Follow Us',
        'contact.form.title': 'Send a Message',
        'contact.form.name': 'Full Name',
        'contact.form.email': 'Email Address',
        'contact.form.subject': 'Subject',
        'contact.form.message': 'Message',
        'contact.form.submit': 'Send Message',
        'contact.form.placeholder.name': 'John Doe',
        'contact.form.placeholder.email': 'john@example.com',
        'contact.form.placeholder.subject': 'Order Inquiry',
        'contact.form.placeholder.message': 'How can we help you?',
        'contact.map.coming': 'Interactive Map Coming Soon',
        'contact.success': 'Thank you for your message! We will get back to you soon.',
        'login.title': 'Welcome Back',
        'login.email': 'Email Address',
        'login.password': 'Password',
        'login.submit': 'Sign In',
        'login.no_account': 'Don\'t have an account?',
        'login.create': 'Create one',
        'login.placeholder.email': 'you@example.com',
        'register.title': 'Create Account',
        'register.name': 'Full Name',
        'register.email': 'Email Address',
        'register.password': 'Password',
        'register.confirm_password': 'Confirm Password',
        'register.submit': 'Sign Up',
        'register.processing': 'Processing...',
        'register.have_account': 'Already have an account?',
        'register.signin': 'Sign in',
        'register.placeholder.name': 'John Doe',
        'register.placeholder.email': 'you@example.com',
        'register.error.password_mismatch': 'Passwords do not match!',
        'register.error.generic': 'Something went wrong',
        'register.error.failed': 'Registration Failed',
        'register.success.otp_sent': 'OTP Sent to',
        'register.success.registered': 'Registration Successful!',
        'register.otp.title': 'Verify Email',
        'register.otp.message': 'Enter the 6-digit code sent to',
        'register.otp.placeholder': 'Enter OTP',
        'register.otp.verify': 'Verify & Login',
        'register.otp.verifying': 'Verifying...',
        'register.otp.cancel': 'Cancel',
        'product.breadcrumb.home': 'Home',
        'product.breadcrumb.shop': 'Shop',
        'product.collection': 'Collection',
        'product.reviews': 'Based on 124 reviews',
        'product.vegan': '100% Vegan',
        'product.eco_packaging': 'Eco Packaging',
        'product.select_size': 'Select Size:',
        'product.add_to_cart': 'Add to Cart',
        'product.free_shipping': 'Free global shipping',
        'product.warranty': '2 Year Warranty',
        'product.tab.description': 'Description',
        'product.tab.nutrition': 'Nutrition Facts',
        'product.tab.shipping': 'Shipping & Returns',
        'product.desc.title': 'Product Description',
        'product.desc.ingredients': 'Ingredients:',
        'product.nutrition.title': 'Nutritional Information',
        'product.shipping.title': 'Shipping Information',
        'product.shipping.text': 'We ship worldwide. Orders processed within 24 hours.',
        'product.shipping.standard': 'Standard Shipping: 5-7 business days',
        'product.shipping.express': 'Express Shipping: 2-3 business days',
        'product.related': 'You May Also Like',
        'product.not_found': 'Product Not Found',
        'product.not_found.desc': 'The requested product does not exist.',
        'admin.dashboard.title': 'Dashboard Overview',
        'admin.sales': 'Total Sales',
        'admin.orders': 'Total Orders',
        'admin.products': 'Total Products',
        'admin.customers': 'Customers',
        'admin.low_stock': 'Low Stock',
        'admin.recent_orders': 'Recent Orders',
        'admin.order_id': 'Order ID',
        'admin.customer': 'Customer',
        'admin.date': 'Date',
        'admin.status': 'Status',
        'admin.total': 'Total',
        'admin.no_orders': 'No orders found',
        'admin.products.title': 'Product Management',
        'admin.products.add': '+ Add New Product',
        'admin.products.id': 'ID',
        'admin.products.name': 'Product Name',
        'admin.products.category': 'Category',
        'admin.products.price': 'Price',
        'admin.products.stock': 'Stock',
        'admin.products.actions': 'Actions',
        'admin.products.edit': 'Edit',
        'admin.products.delete': 'Delete',
        'admin.products.delete_confirm': 'Are you sure you want to delete this product?',
        'admin.orders.title': 'Order Management',
        'admin.orders.payment': 'Payment',
        'admin.orders.view': 'View',
        'admin.orders.no_orders': 'No orders found.',
        'admin.coupons.title': 'Coupon Management',
        'admin.coupons.add': 'Add Coupon',
        'admin.coupons.form_title': 'Add New Coupon',
        'admin.coupons.code': 'Coupon Code',
        'admin.coupons.code_placeholder': 'SUMMER25',
        'admin.coupons.expiration': 'Expiration Date',
        'admin.coupons.discount_type': 'Discount Type',
        'admin.coupons.discount_value': 'Discount Value',
        'admin.coupons.type_percentage': 'Percentage (%)',
        'admin.coupons.type_fixed': 'Fixed Amount ($)',
        'admin.coupons.create': 'Create Coupon',
        'admin.coupons.discount': 'Discount',
        'admin.coupons.expires': 'Expires',
        'admin.coupons.active': 'Active',
        'admin.coupons.inactive': 'Inactive',
        'admin.coupons.delete_title': 'Delete Coupon',
        'admin.coupons.no_coupons': 'No coupons found.',
        'admin.order_view.back': 'Back to Orders',
        'admin.order_view.order': 'Order',
        'admin.order_view.placed': 'Placed on',
        'admin.order_view.pending': 'Pending',
        'admin.order_view.processing': 'Processing',
        'admin.order_view.shipped': 'Shipped',
        'admin.order_view.completed': 'Completed',
        'admin.order_view.cancelled': 'Cancelled',
        'admin.order_view.items': 'Items',
        'admin.order_view.product': 'Product',
        'admin.order_view.quantity': 'Quantity',
        'admin.order_view.subtotal': 'Subtotal',
        'admin.order_view.shipping': 'Shipping',
        'admin.order_view.customer_details': 'Customer Details',
        'admin.order_view.shipping_address': 'Shipping Address',
        'admin.order_view.no_address': 'No address provided',
        'admin.order_view.payment_info': 'Payment Info',
        'admin.order_view.paid': 'PAID',
        'admin.order_view.not_found': 'Order not found',
        'admin.add_product.title': 'Add New Product',
        'admin.add_product.name': 'Product Name',
        'admin.add_product.name_placeholder': 'e.g. Organic Basil Oil',
        'admin.add_product.price': 'Price ($)',
        'admin.add_product.stock': 'Stock Quantity',
        'admin.add_product.image': 'Product Image',
        'admin.add_product.image_url': 'Image URL',
        'admin.add_product.upload_file': 'Upload File',
        'admin.add_product.url_placeholder': 'https://example.com/image.jpg',
        'admin.add_product.gallery': 'Gallery Images (Optional)',
        'admin.add_product.description': 'Description',
        'admin.add_product.desc_placeholder': 'Product description...',
        'admin.add_product.cancel': 'Cancel',
        'admin.add_product.save': 'Save Product',
        'admin.add_product.success': 'Product Added Successfully!',
        'admin.add_product.error_image': 'Please select an image file.',
        'admin.add_product.error_url': 'Please enter an image URL.',
        'admin.add_product.error_file': 'Failed to read image file.',
        'admin.edit_product.title': 'Edit Product',
        'admin.edit_product.update': 'Update Product',
        'admin.edit_product.success': 'Product Updated Successfully!',
        'admin.edit_product.not_found': 'Product not found',
        'admin.edit_product.loading': 'Loading...',
        'admin.edit_product.gallery_label': 'Gallery Images',
        'dashboard': 'Dashboard',
        'products': 'Products',
        'orders': 'Orders',
        'coupons': 'Coupons',
        'back_to_store': 'Back to Store',
        'logout': 'Logout',
        'admin.nav.dashboard': 'Dashboard',
        'admin.nav.products': 'Products',
        'admin.nav.orders': 'Orders',
        'admin.nav.coupons': 'Coupons',
        'admin.nav.back_to_store': 'Back to Store',
        'admin.nav.logout': 'Logout',
    },
    hi: {
        'nav.home': 'होम',
        'nav.products': 'उत्पाद',
        'nav.about': 'हमारे बारे में',
        'nav.contact': 'संपर्क करें',
        'nav.login': 'लॉग इन',
        'nav.logout': 'लॉग आउट',
        'hero.title': 'प्रीमियम जैतून तेल',
        'hero.subtitle': 'हमारे कोल्ड-प्रेस्ड जैतून के तेल के साथ प्रकृति की शुद्धता का अनुभव करें।',
        'hero.cta': 'अभी खरीदें',
        'footer.text': '© 2026 ग्रीन गोल्ड। सर्वाधिकार सुरक्षित।',
        'cart.title': 'आपकी शॉपिंग कार्ट',
        'cart.checkout': 'चेकआउट के लिए आगे बढ़ें',
        'common.loading': 'लोड हो रहा है...',
        'home.hero.title': 'प्रकृति से शुद्ध सोना',
        'home.hero.subtitle': 'प्रीमियम, कोल्ड-प्रेस्ड ग्रीन गोल्ड (जैतून तेल) की समृद्धि का अनुभव करें।',
        'home.why': 'ग्रीन गोल्ड क्यों चुनें?',
        'home.featured': 'विशेष संग्रह',
        'home.about.title': 'पवित्रता का सार',
        'home.testimonials': 'हमारे ग्राहक क्या कहते हैं',
        'product.organic.title': 'ऑर्गेनिक एक्स्ट्रा वर्जिन जैतून तेल',
        'product.cold.title': 'कोल्ड प्रेस्ड जैतून तेल',
        'product.garlic.title': 'लहसुन युक्त जैतून तेल',
        'product.skin.title': 'स्किन केयर जैतून तेल',
        'category.premium': 'प्रीमियम',
        'category.classic': 'क्लासिक',
        'category.infused': 'इन्फ्यूज्ड',
        'category.beauty': 'ब्यूटी',
        'footer.desc': 'जैविक खेतों से शुद्धतम, कोल्ड-प्रेस्ड जैतून का तेल सीधे आपकी रसोई में। स्वास्थ्य के स्वर्ण मानक का अनुभव करें।',
        'footer.quick': 'त्वरित लिंक',
        'footer.customer': 'ग्राहक सेवा',
        'footer.stay': 'अपडेट रहें',
        'footer.sub': 'विशेष प्रस्तावों और स्वास्थ्य सुझावों के लिए सदस्यता लें।',
        'footer.join': 'शामिल हों',
        'feature.pure.title': '100% शुद्ध',
        'feature.pure.desc': 'वर्जिन और ऑर्गेनिक, सीधे खेत से।',
        'feature.cold.title': 'कोल्ड प्रेस्ड',
        'feature.cold.desc': 'सभी प्राकृतिक पोषक तत्वों और स्वाद को बरकरार रखता है।',
        'feature.chem.title': 'कोई रसायन नहीं',
        'feature.chem.desc': 'शून्य एडिटिव्स, प्रिजर्वेटिव्स, या कृत्रिम रंग।',
        'feature.lab.title': 'लैब परीक्षित',
        'feature.lab.desc': 'गुणवत्ता और शुद्धता के लिए प्रमाणित।',
        'about.text': 'हमारी यात्रा एक साधारण मिशन के साथ शुरू हुई: भूमध्यसागरीय जैतून के तेल का प्रामाणिक स्वाद और स्वास्थ्य लाभ आपकी मेज पर लाना। ग्रीन गोल्ड की हर बोतल गुणवत्ता का वादा है, प्राचीन पेड़ों से काटा गया और इसकी प्राकृतिक अच्छाई को संरक्षित करने के लिए कोल्ड-प्रेस्ड।',
        'testimonial.quote': 'बिल्कुल सबसे अच्छा जैतून का तेल जो मैंने कभी चखा है। स्वाद समृद्ध और प्रामाणिक है। मैं इसका उपयोग खाना पकाने से लेकर सलाद तक हर चीज के लिए करता हूं!',
        'about.cta': 'हमारी कहानी पढ़ें',
        'footer.shipping': 'शिपिंग नीति',
        'footer.returns': 'वापसी और रिफंड',
        'footer.privacy': 'गोपनीयता नीति',
        'footer.terms': 'सेवा की शर्तें',
        'home.cert.title': 'उत्कृष्टता के लिए प्रमाणित',
        'cert.fssai': 'FSSAI प्रमाणित',
        'cert.organic': '100% जैविक',
        'cert.iso': 'ISO 9001:2015',
        'shop.title': 'हमारा संग्रह',
        'shop.filters.categories': 'श्रेणियाँ',
        'shop.filters.price': 'मूल्य सीमा',
        'shop.filters.size': 'आकार',
        'shop.filters.price_text': 'मूल्य',
        'category.all': 'सभी',
        'category.bestsellers': 'सबसे ज्यादा बिकने वाला',
        'shop.showing': 'दिखा रहा है',
        'shop.results': 'परिणाम',
        'shop.sort.pop': 'लोकप्रियता के आधार पर',
        'shop.sort.low': 'मूल्य: कम से ज्यादा',
        'shop.sort.high': 'मूल्य: ज्यादा से कम',
        'shop.no_products': 'इस श्रेणी में कोई उत्पाद नहीं मिला।',
        'product.truffle.title': 'ट्रफल इन्फ्यूज्ड तेल',
        'product.hair.title': 'हेयर केयर अमृत',
        'Premium': 'प्रीमियम',
        'Classic': 'क्लासिक',
        'Infused': 'इन्फ्यूज्ड',
        'Beauty': 'ब्यूटी',
        'about.hero.title': 'परंपराओं को संजोना',
        'about.hero.subtitle': '1985 से, ग्रीन गोल्ड दुनिया का बेहतरीन जैविक जैतून तेल बनाने के लिए समर्पित है, प्राचीन तरीकों को संरक्षित करते हुए और आधुनिक स्थिरता को अपनाते हुए।',
        'about.story.title': 'प्रकृति में निहित',
        'about.story.p1': 'यह सब स्पेन के अंडालूसिया की धूप से सराबोर पहाड़ियों में शुरू हुआ। हमारे संस्थापक, गार्सिया परिवार का मानना था कि सच्ची गुणवत्ता भूमि के प्रति गहरे सम्मान से आती है। पीढ़ियों से, हमने कठोर रसायनों या कीटनाशकों के उपयोग के बिना अपने जैतून के पेड़ों की देखभाल की है।',
        'about.story.p2': 'ग्रीन गोल्ड की हर बोतल धैर्य और जुनून की कहानी कहती है। हम अपने जैतून को पकने के चरम पर काटते हैं और प्रकृति के इरादे के अनुसार जीवंत स्वाद और शक्तिशाली एंटीऑक्सिडेंट को पकड़ने के लिए उन्हें घंटों के भीतर कोल्ड-प्रेस करते हैं।',
        'about.story.p3': 'आज, हमें दुनिया भर के परिवारों के साथ इस स्वर्ण तरल को साझा करने पर गर्व है, जो आपकी रसोई में भूमध्यसागरीय स्वास्थ्य और विलासिता का स्पर्श लाता है।',
        'about.stat.exp': 'वर्षों का अनुभव',
        'about.stat.acres': 'एकड़ के बाग',
        'about.stat.cust': 'खुश ग्राहक',
        'about.stat.cert': 'जैविक प्रमाणित',
        'about.values.title': 'हमारे मूल मूल्य',
        'value.sus.title': 'स्थिरता',
        'value.sus.desc': 'हम यह सुनिश्चित करने के लिए पुनर्योजी कृषि का अभ्यास करते हैं कि हमारी भूमि आने वाली पीढ़ियों के लिए पनपे।',
        'value.int.title': 'अखंडता',
        'value.int.desc': 'पारदर्शिता महत्वपूर्ण है। हम पेड़ से बोतल तक बेजोड़ शुद्धता की गारंटी देते हैं।',
        'value.com.title': 'समुदाय',
        'value.com.desc': 'हम निष्पक्ष व्यापार का समर्थन करते हैं और हर क्षेत्र में स्थानीय किसानों को सशक्त बनाते हैं जहाँ हम काम करते हैं।',
        'value.exc.title': 'उत्कृष्टता',
        'value.exc.desc': 'दुनिया भर के शीर्ष शेफ और स्वास्थ्य विशेषज्ञों द्वारा मान्यता प्राप्त पुरस्कार विजेता गुणवत्ता।',
        'benefits.title': 'स्वास्थ्य का स्वर्ण अमृत',
        'benefits.subtitle': 'जैतून के तेल के विज्ञान-समर्थित लाभों की खोज करें',
        'benefits.heart.title': 'हृदय स्वास्थ्य',
        'benefits.heart.desc': 'जैतून का तेल मोनोअनसैचुरेटेड वसा से भरपूर होता है, जो खराब कोलेस्ट्रॉल (LDL) को कम करने और स्वस्थ रक्तचाप के स्तर को बनाए रखने में मदद करता है। यह हृदय-स्वस्थ भूमध्यसागरीय आहार का एक आधार है।',
        'benefits.weight.title': 'वजन प्रबंधन',
        'benefits.weight.desc': 'वसा होने के बावजूद, जैतून का तेल वजन घटाने में सहायता कर सकता है। स्वस्थ वसा तृप्ति बढ़ाती है, जिससे आप लंबे समय तक भरा हुआ महसूस करते हैं और अस्वास्थ्यकर खाद्य पदार्थों पर नाश्ता करने की इच्छा कम हो जाती है।',
        'benefits.skin.title': 'त्वचा और बालों की देखभाल',
        'benefits.skin.desc': 'विटामिन ई और एंटीऑक्सिडेंट से भरपूर, जैतून का तेल त्वचा को पोषण देता है, उम्र बढ़ने के संकेतों से लड़ता है, और बालों को जड़ से सिरे तक मजबूत करता है। यह एक प्राकृतिक मॉइस्चराइज़र और रक्षक है।',
        'benefits.anti.title': 'सूजन-रोधी',
        'benefits.anti.desc': 'इसमें ओलियोकैंथल होता है, जो इबुप्रोफेन के समान शक्तिशाली सूजन-रोधी गुणों वाला एक यौगिक है। यह शरीर में सूजन को कम करने और समग्र प्रतिरक्षा का समर्थन करने में मदद करता है।',
        'benefits.science.title': 'विज्ञान द्वारा समर्थित',
        'benefits.science.text': 'जैतून के तेल में मुख्य रूप से ओलिक एसिड (83% तक) होता है, जिसमें लिनोलिक एसिड (21% तक) और पामिटिक एसिड (20% तक) सहित अन्य फैटी एसिड की छोटी मात्रा होती है। अध्ययनों से पता चला है कि संतृप्त वसा को असंतृप्त वसा जैसे जैतून के तेल में पाए जाने वाले वसा से बदलने से हृदय संबंधी घटनाओं का जोखिम कम हो जाता है।',
        'blog.title': 'ऑलिव ब्लॉग और रेसिपी',
        'blog.subtitle': 'स्वस्थ जीवन की दुनिया से टिप्स, ट्रिक्स और कहानियां।',
        'blog.post1.title': 'जैतून के तेल के साथ 5 आसान सलाद ड्रेसिंग',
        'blog.post1.excerpt': 'इन सरल, स्वस्थ और स्वादिष्ट घर के बने ड्रेसिंग के साथ अपने सलाद को बेहतर बनाएं।',
        'blog.post2.title': 'क्या आप एक्स्ट्रा वर्जिन ऑलिव ऑयल से फ्राई कर सकते हैं?',
        'blog.post2.excerpt': 'स्मोक पॉइंट और प्रीमियम जैतून के तेल के साथ खाना पकाने के आसपास के मिथकों को तोड़ना।',
        'blog.post3.title': 'भूमध्यसागरीय आहार के लिए अंतिम गाइड',
        'blog.post3.excerpt': 'अधिकतम स्वास्थ्य लाभ के लिए अपने दैनिक आहार में तरल सोने को कैसे शामिल करें।',
        'blog.category.recipes': 'रेसिपी',
        'blog.category.cooking': 'खाना पकाने की युक्तियाँ',
        'blog.category.health': 'स्वास्थ्य',
        'blog.readmore': 'और पढ़ें',
        'blog.back': 'ब्लॉग पर वापस जाएं',
        'blog.share': 'इस लेख को साझा करें',
        'blog.recent': 'हाल के पोस्ट',
        'blog.categories': 'श्रेणियाँ',
        'contact.hero.title': 'संपर्क में रहें',
        'contact.hero.subtitle': 'हमारे उत्पादों या साझेदारी के अवसरों के बारे में प्रश्न हैं? हम आपसे सुनना पसंद करेंगे।',
        'contact.call.title': 'हमें कॉल करें',
        'contact.call.hours': 'सोम-शुक्र, सुबह 9 बजे - शाम 6 बजे EST',
        'contact.email.title': 'हमें ईमेल करें',
        'contact.visit.title': 'हमसे मिलें',
        'contact.follow': 'हमें फॉलो करें',
        'contact.form.title': 'संदेश भेजें',
        'contact.form.name': 'पूरा नाम',
        'contact.form.email': 'ईमेल पता',
        'contact.form.subject': 'विषय',
        'contact.form.message': 'संदेश',
        'contact.form.submit': 'संदेश भेजें',
        'contact.form.placeholder.name': 'जॉन डो',
        'contact.form.placeholder.email': 'john@example.com',
        'contact.form.placeholder.subject': 'ऑर्डर पूछताछ',
        'contact.form.placeholder.message': 'हम आपकी कैसे मदद कर सकते हैं?',
        'contact.map.coming': 'इंटरैक्टिव मैप जल्द आ रहा है',
        'contact.success': 'आपके संदेश के लिए धन्यवाद! हम जल्द ही आपसे संपर्क करेंगे।',
        'login.title': 'वापस स्वागत है',
        'login.email': 'ईमेल पता',
        'login.password': 'पासवर्ड',
        'login.submit': 'साइन इन करें',
        'login.no_account': 'खाता नहीं है?',
        'login.create': 'एक बनाएं',
        'login.placeholder.email': 'you@example.com',
        'register.title': 'खाता बनाएं',
        'register.name': 'पूरा नाम',
        'register.email': 'ईमेल पता',
        'register.password': 'पासवर्ड',
        'register.confirm_password': 'पासवर्ड की पुष्टि करें',
        'register.submit': 'साइन अप करें',
        'register.processing': 'प्रोसेसिंग...',
        'register.have_account': 'पहले से खाता है?',
        'register.signin': 'साइन इन करें',
        'register.placeholder.name': 'जॉन डो',
        'register.placeholder.email': 'you@example.com',
        'register.error.password_mismatch': 'पासवर्ड मेल नहीं खाते!',
        'register.error.generic': 'कुछ गलत हो गया',
        'register.error.failed': 'पंजीकरण विफल',
        'register.success.otp_sent': 'OTP भेजा गया',
        'register.success.registered': 'पंजीकरण सफल!',
        'register.otp.title': 'ईमेल सत्यापित करें',
        'register.otp.message': 'भेजे गए 6-अंकीय कोड दर्ज करें',
        'register.otp.placeholder': 'OTP दर्ज करें',
        'register.otp.verify': 'सत्यापित करें और लॉगिन करें',
        'register.otp.verifying': 'सत्यापित कर रहे हैं...',
        'register.otp.cancel': 'रद्द करें',
        'product.breadcrumb.home': 'होम',
        'product.breadcrumb.shop': 'दुकान',
        'product.collection': 'संग्रह',
        'product.reviews': '124 समीक्षाओं के आधार पर',
        'product.vegan': '100% शाकाहारी',
        'product.eco_packaging': 'इको पैकेजिंग',
        'product.select_size': 'आकार चुनें:',
        'product.add_to_cart': 'कार्ट में जोड़ें',
        'product.free_shipping': 'मुफ्त वैश्विक शिपिंग',
        'product.warranty': '2 साल की वारंटी',
        'product.tab.description': 'विवरण',
        'product.tab.nutrition': 'पोषण तथ्य',
        'product.tab.shipping': 'शिपिंग और रिटर्न',
        'product.desc.title': 'उत्पाद विवरण',
        'product.desc.ingredients': 'सामग्री:',
        'product.nutrition.title': 'पोषण संबंधी जानकारी',
        'product.shipping.title': 'शिपिंग जानकारी',
        'product.shipping.text': 'हम दुनिया भर में शिप करते हैं। 24 घंटे के भीतर ऑर्डर प्रोसेस किए जाते हैं।',
        'product.shipping.standard': 'मानक शिपिंग: 5-7 व्यावसायिक दिन',
        'product.shipping.express': 'एक्सप्रेस शिपिंग: 2-3 व्यावसायिक दिन',
        'product.related': 'आपको यह भी पसंद आ सकता है',
        'product.not_found': 'उत्पाद नहीं मिला',
        'product.not_found.desc': 'अनुरोधित उत्पाद मौजूद नहीं है।',
        'admin.dashboard.title': 'डैशबोर्ड अवलोकन',
        'admin.sales': 'कुल बिक्री',
        'admin.orders': 'कुल ऑर्डर',
        'admin.products': 'कुल उत्पाद',
        'admin.customers': 'ग्राहक',
        'admin.low_stock': 'कम स्टॉक',
        'admin.recent_orders': 'हाल के ऑर्डर',
        'admin.order_id': 'ऑर्डर ID',
        'admin.customer': 'ग्राहक',
        'admin.date': 'तारीख',
        'admin.status': 'स्थिति',
        'admin.total': 'कुल',
        'admin.no_orders': 'कोई ऑर्डर नहीं मिला',
        'admin.products.title': 'उत्पाद प्रबंधन',
        'admin.products.add': '+ नया उत्पाद जोड़ें',
        'admin.products.id': 'ID',
        'admin.products.name': 'उत्पाद का नाम',
        'admin.products.category': 'श्रेणी',
        'admin.products.price': 'कीमत',
        'admin.products.stock': 'स्टॉक',
        'admin.products.actions': 'कार्रवाई',
        'admin.products.edit': 'संपादित करें',
        'admin.products.delete': 'हटाएं',
        'admin.products.delete_confirm': 'क्या आप वाकई इस उत्पाद को हटाना चाहते हैं?',
        'admin.orders.title': 'ऑर्डर प्रबंधन',
        'admin.orders.payment': 'भुगतान',
        'admin.orders.view': 'देखें',
        'admin.orders.no_orders': 'कोई ऑर्डर नहीं मिला।',
        'admin.coupons.title': 'कूपन प्रबंधन',
        'admin.coupons.add': 'कूपन जोड़ें',
        'admin.coupons.form_title': 'नया कूपन जोड़ें',
        'admin.coupons.code': 'कूपन कोड',
        'admin.coupons.code_placeholder': 'SUMMER25',
        'admin.coupons.expiration': 'समाप्ति तिथि',
        'admin.coupons.discount_type': 'छूट प्रकार',
        'admin.coupons.discount_value': 'छूट मूल्य',
        'admin.coupons.type_percentage': 'प्रतिशत (%)',
        'admin.coupons.type_fixed': 'निश्चित राशि ($)',
        'admin.coupons.create': 'कूपन बनाएं',
        'admin.coupons.discount': 'छूट',
        'admin.coupons.expires': 'समाप्त होता है',
        'admin.coupons.active': 'सक्रिय',
        'admin.coupons.inactive': 'निष्क्रिय',
        'admin.coupons.delete_title': 'कूपन हटाएं',
        'admin.coupons.no_coupons': 'कोई कूपन नहीं मिला।',
        'admin.order_view.back': 'ऑर्डर पर वापस जाएं',
        'admin.order_view.order': 'ऑर्डर',
        'admin.order_view.placed': 'रखा गया',
        'admin.order_view.pending': 'लंबित',
        'admin.order_view.processing': 'प्रोसेसिंग',
        'admin.order_view.shipped': 'भेज दिया गया',
        'admin.order_view.completed': 'पूर्ण',
        'admin.order_view.cancelled': 'रद्द',
        'admin.order_view.items': 'आइटम',
        'admin.order_view.product': 'उत्पाद',
        'admin.order_view.quantity': 'मात्रा',
        'admin.order_view.subtotal': 'उपयोग',
        'admin.order_view.shipping': 'शिपिंग',
        'admin.order_view.customer_details': 'ग्राहक विवरण',
        'admin.order_view.shipping_address': 'शिपिंग पता',
        'admin.order_view.no_address': 'कोई पता प्रदान नहीं किया गया',
        'admin.order_view.payment_info': 'भुगतान जानकारी',
        'admin.order_view.paid': 'भुगतान किया',
        'admin.order_view.not_found': 'ऑर्डर नहीं मिला',
        'admin.add_product.title': 'नया उत्पाद जोड़ें',
        'admin.add_product.name': 'उत्पाद का नाम',
        'admin.add_product.name_placeholder': 'जैसे ऑर्गेनिक बेसिल ऑयल',
        'admin.add_product.price': 'कीमत ($)',
        'admin.add_product.stock': 'स्टॉक मात्रा',
        'admin.add_product.image': 'उत्पाद छवि',
        'admin.add_product.image_url': 'छवि URL',
        'admin.add_product.upload_file': 'फ़ाइल अपलोड करें',
        'admin.add_product.url_placeholder': 'https://example.com/image.jpg',
        'admin.add_product.gallery': 'गैलरी छवियाँ (वैकल्पिक)',
        'admin.add_product.description': 'विवरण',
        'admin.add_product.desc_placeholder': 'उत्पाद विवरण...',
        'admin.add_product.cancel': 'रद्द करें',
        'admin.add_product.save': 'उत्पाद सहेजें',
        'admin.add_product.success': 'उत्पाद सफलतापूर्वक जोड़ा गया!',
        'admin.add_product.error_image': 'कृपया एक छवि फ़ाइल चुनें।',
        'admin.add_product.error_url': 'कृपया एक छवि URL दर्ज करें।',
        'admin.add_product.error_file': 'छवि फ़ाइल पढ़ने में विफल।',
        'admin.edit_product.title': 'उत्पाद संपादित करें',
        'admin.edit_product.update': 'उत्पाद अपडेट करें',
        'admin.edit_product.success': 'उत्पाद सफलतापूर्वक अपडेट किया गया!',
        'admin.edit_product.not_found': 'उत्पाद नहीं मिला',
        'admin.edit_product.loading': 'लोड हो रहा है...',
        'admin.edit_product.gallery_label': 'गैलरी छवियाँ',
        'dashboard': 'डैशबोर्ड',
        'products': 'उत्पाद',
        'orders': 'ऑर्डर',
        'coupons': 'कूपन',
        'back_to_store': 'स्टोर पर वापस जाएं',
        'logout': 'लॉगआउट',
        'admin.nav.dashboard': 'डैशबोर्ड',
        'admin.nav.products': 'उत्पाद',
        'admin.nav.orders': 'ऑर्डर',
        'admin.nav.coupons': 'कूपन',
        'admin.nav.back_to_store': 'स्टोर पर वापस जाएं',
        'admin.nav.logout': 'लॉगआउट',
    },
    es: {
        'nav.home': 'Inicio',
        'nav.products': 'Productos',
        'nav.about': 'Sobre nosotros',
        'nav.contact': 'Contacto',
        'nav.login': 'Iniciar sesión',
        'nav.logout': 'Cerrar sesión',
        'hero.title': 'Aceite de Olive Premium',
        'hero.subtitle': 'Experimente la pureza de la naturaleza con nuestro aceite de oliva prensado en frío.',
        'hero.cta': 'Compra ahora',
        'footer.text': '© 2026 Green Gold. Todos los derechos reservados.',
        'cart.title': 'Tu carrito de compras',
        'cart.checkout': 'Pasar por la caja',
        'common.loading': 'Cargando...',
        'home.hero.title': 'Oro puro de la naturaleza',
        'home.hero.subtitle': 'Experimente la riqueza del Green Gold (aceite de oliva) premium prensado en frío.',
        'home.why': '¿Por qué elegir Green Gold?',
        'home.featured': 'Colecciones destacadas',
        'home.about.title': 'La esencia de la pureza',
        'home.testimonials': 'Lo que dicen nuestros clientes',
    },
    fr: {
        'nav.home': 'Accueil',
        'nav.products': 'Produits',
        'nav.about': 'À propos',
        'nav.contact': 'Contact',
        'nav.login': 'Connexion',
        'nav.logout': 'Déconnexion',
        'hero.title': 'Huile de Olive Premium',
        'hero.subtitle': 'Découvrez la pureté de la nature avec notre huile d\'olive pressée à froid.',
        'hero.cta': 'Acheter maintenant',
        'footer.text': '© 2026 Green Gold. Tous droits réservés.',
        'cart.title': 'Votre panier',
        'cart.checkout': 'Passer à la caisse',
        'common.loading': 'Chargement...',
        'home.hero.title': 'De l\'or pur de la nature',
        'home.hero.subtitle': 'Découvrez la richesse de l\'or vert (huile d\'olive) pressé à froid de première qualité.',
        'home.why': 'Pourquoi choisir Green Gold ?',
        'home.featured': 'Collections en vedette',
        'home.about.title': 'L\'essence de la pureté',
        'home.testimonials': 'Ce que disent nos clients',
    },
    de: {
        'nav.home': 'Startseite',
        'nav.products': 'Produkte',
        'nav.about': 'Über uns',
        'nav.contact': 'Kontakt',
        'nav.login': 'Anmelden',
        'nav.logout': 'Abmelden',
        'hero.title': 'Premium Olive Öl',
        'hero.subtitle': 'Erleben Sie die Reinheit der Natur mit unserem kaltgepressten Olivenöl.',
        'hero.cta': 'Jetzt kaufen',
        'footer.text': '© 2026 Green Gold. Alle Rechte vorbehalten.',
        'cart.title': 'Ihr Warenkorb',
        'cart.checkout': 'Zur Kasse',
        'common.loading': 'Laden...',
        'home.hero.title': 'Pures Gold aus der Natur',
        'home.hero.subtitle': 'Erleben Sie den Reichtum von hochwertigem, kaltgepresstem Green Gold (Olivenöl).',
        'home.why': 'Warum Green Gold wählen?',
        'home.featured': 'Vorgestellte Kollektionen',
        'home.about.title': 'Die Essenz der Reinheit',
        'home.testimonials': 'Was unsere Kunden sagen',
    },
    it: {
        'nav.home': 'Home', 'nav.products': 'Prodotti', 'nav.about': 'Chi siamo', 'nav.contact': 'Contatti',
        'nav.login': 'Accedi', 'nav.logout': 'Esci',
        'hero.title': 'Olio Olive Premium', 'hero.subtitle': 'Scopri la purezza della natura con il nostro olio d\'oliva spremuto a freddo.', 'hero.cta': 'Acquista ora',
        'footer.text': '© 2026 Green Gold. Tutti i diritti riservati.',
        'cart.title': 'Il tuo carrello', 'cart.checkout': 'Procedi al checkout', 'common.loading': 'Caricamento...',
        'home.hero.title': 'Oro Puro dalla Natura',
        'home.hero.subtitle': 'Scopri la ricchezza del Green Gold (Olio d\'Oliva) premium spremuto a freddo. Provenienza globale, consegna locale.',
        'home.why': 'Perché scegliere Green Gold?',
        'home.featured': 'Collezioni in Evidenza',
        'home.about.title': 'L\'Essenza della Purezza',
        'home.testimonials': 'Cosa dicono i nostri clienti',
        'product.organic.title': 'Olio Extra Vergine di Oliva Biologico',
        'product.cold.title': 'Olio Olive Spremuto a Freddo',
        'product.garlic.title': 'Olio d\'Oliva all\'Aglio',
        'product.skin.title': 'Olio d\'Oliva per la Pelle',
        'category.premium': 'Premium',
        'category.classic': 'Classico',
        'category.infused': 'Infuso',
        'category.beauty': 'Bellezza',
        'footer.desc': 'Portare l\'olio d\'oliva più puro e spremuto a freddo dalle fattorie biologiche direttamente alla tua cucina. Scopri lo standard d\'oro della salute.',
        'footer.quick': 'Link Veloci',
        'footer.customer': 'Servizio Clienti',
        'footer.stay': 'Rimani Aggiornato',
        'footer.sub': 'Iscriviti per offerte esclusive e consigli sulla salute.',
        'footer.join': 'Iscriviti',
        'feature.pure.title': '100% Puro',
        'feature.pure.desc': 'Vergine e biologico, direttamente dalla fattoria.',
        'feature.cold.title': 'Spremuto a Freddo',
        'feature.cold.desc': 'Mantiene tutti i nutrienti naturali e il sapore.',
        'feature.chem.title': 'Nessuna Chimica',
        'feature.chem.desc': 'Zero additivi, conservanti o coloranti artificiali.',
        'feature.lab.title': 'Testato in Laboratorio',
        'feature.lab.desc': 'Certificato per qualità e purezza.',
        'about.text': 'Il nostro viaggio è iniziato con una missione semplice: portare il gusto autentico e i benefici per la salute dell\'olio d\'oliva mediterraneo alla tua tavola. Ogni bottiglia di Green Gold è una promessa di qualità, raccolta da antichi uliveti e spremuta a freddo per preservare la sua bontà naturale.',
        'testimonial.quote': 'Assolutamente il miglior olio d\'oliva che abbia mai assaggiato. Il sapore è ricco e autentico. Lo uso per tutto, dalla cucina alle insalate!',
        'about.cta': 'Leggi la nostra storia',
        'footer.shipping': 'Politica di Spedizione',
        'footer.returns': 'Resi e Rimborsi',
        'footer.privacy': 'Politica sulla Privacy',
        'footer.terms': 'Termini di Servizio',
        'home.cert.title': 'Certificato per l\'Eccellenza',
        'cert.fssai': 'Certificato FSSAI',
        'cert.organic': '100% Biologico',
        'cert.iso': 'ISO 9001:2015',
        'shop.title': 'La Nostra Collezione',
        'shop.filters.categories': 'Categorie',
        'shop.filters.price': 'Fascia di Prezzo',
        'shop.filters.size': 'Taglia',
        'shop.filters.price_text': 'Prezzo',
        'category.all': 'Tutti',
        'category.bestsellers': 'Più Venduti',
        'shop.showing': 'Mostrando',
        'shop.results': 'risultati',
        'shop.sort.pop': 'Ordina per Popolarità',
        'shop.sort.low': 'Prezzo: Basso - Alto',
        'shop.sort.high': 'Prezzo: Alto - Basso',
        'shop.no_products': 'Nessun prodotto trovato in questa categoria.',
        'product.truffle.title': 'Olio al Tartufo',
        'product.hair.title': 'Elisir per Capelli',
        'Premium': 'Premium',
        'Classic': 'Classico',
        'Infused': 'Infuso',
        'Beauty': 'Bellezza',
        'about.hero.title': 'Coltivare Tradizioni',
        'about.hero.subtitle': 'Dal 1985, Olive Oil si dedica alla produzione del miglior olio d\'oliva biologico al mondo, preservando metodi antichi pur abbracciando la sostenibilità moderna.',
        'about.story.title': 'Radicati nella Natura',
        'about.story.p1': 'Tutto è iniziato sulle colline soleggiate dell\'Andalusia, in Spagna. La nostra famiglia fondatrice, i Garcia, credeva che la vera qualità nascesse da un profondo rispetto per la terra. Da generazioni, curiamo i nostri uliveti senza l\'uso di prodotti chimici aggressivi o pesticidi.',
        'about.story.p2': 'Ogni bottiglia di Olive Oil racconta una storia di pazienza e passione. Raccogliamo le nostre olive al culmine della maturazione e le spremiamo a freddo entro poche ore per catturare i sapori vibranti e i potenti antiossidanti che la natura ha inteso.',
        'about.story.p3': 'Oggi, siamo orgogliosi di condividere questo oro liquido con le famiglie di tutto il mondo, portando un tocco di salute e lusso mediterraneo nella tua cucina.',
        'about.stat.exp': 'Anni di Esperienza',
        'about.stat.acres': 'Acri di Uliveti',
        'about.stat.cust': 'Clienti Soddisfatti',
        'about.stat.cert': 'Certificato Biologico',
        'about.values.title': 'I Nostri Valori Fondamentali',
        'value.sus.title': 'Sostenibilità',
        'value.sus.desc': 'Pratichiamo un\'agricoltura rigenerativa per garantire che la nostra terra prosperi per le generazioni future.',
        'value.int.title': 'Integrità',
        'value.int.desc': 'La trasparenza è fondamentale. Garantiamo una purezza senza pari dall\'albero alla bottiglia.',
        'value.com.title': 'Comunità',
        'value.com.desc': 'Sosteniamo il commercio equo e diamo potere agli agricoltori locali in ogni regione in cui operiamo.',
        'value.exc.title': 'Eccellenza',
        'value.exc.desc': 'Qualità pluripremiata riconosciuta dai migliori chef ed esperti di salute in tutto il mondo.',
        'benefits.title': 'L\'Elisir d\'Oro della Salute',
        'benefits.subtitle': 'Scopri i benefici scientificamente provati dell\'olio d\'oliva',
        'benefits.heart.title': 'Salute del Cuore',
        'benefits.heart.desc': 'L\'olio d\'oliva è ricco di grassi monoinsaturi, che aiutano a ridurre il colesterolo cattivo (LDL) e a mantenere livelli sani di pressione sanguigna. È una pietra miliare della dieta mediterranea salutare per il cuore.',
        'benefits.weight.title': 'Gestione del Peso',
        'benefits.weight.desc': 'Nonostante sia un grasso, l\'olio d\'oliva può aiutare nella perdita di peso. I grassi sani aumentano la sazietà, aiutandoti a sentirti pieno più a lungo e riducendo l\'impulso di fare spuntini con cibi non salutari.',
        'benefits.skin.title': 'Cura della Pelle e dei Capelli',
        'benefits.skin.desc': 'Ricco di vitamina E e antiossidanti, l\'olio d\'oliva nutre la pelle, combatte i segni dell\'invecchiamento e rafforza i capelli dalla radice alla punta. È un idratante e protettore naturale.',
        'benefits.anti.title': 'Antinfiammatorio',
        'benefits.anti.desc': 'Contiene oleocantale, un composto con potenti proprietà antinfiammatorie simili all\'ibuprofene. Aiuta a ridurre l\'infiammazione nel corpo e supporta l\'immunità generale.',
        'benefits.science.title': 'Supportato dalla Scienza',
        'benefits.science.text': 'L\'olio d\'oliva consiste principalmente di acido oleico (fino all\'83%), con quantità minori di altri acidi grassi tra cui acido linoleico (fino al 21%) e acido palmitico (fino al 20%). Gli studi hanno dimostrato che sostituire i grassi saturi con grassi insaturi come quelli presenti nell\'olio d\'oliva riduce il rischio di eventi cardiovascolari.',
        'blog.title': 'Blog e Ricette sull\'Olio d\'Oliva',
        'blog.subtitle': 'Consigli, trucchi e storie dal mondo della vita sana.',
        'blog.post1.title': '5 Condimenti per Insalata Facili con Olio d\'Oliva',
        'blog.post1.excerpt': 'Migliora le tue insalate con questi condimenti fatti in casa semplici, sani e deliziosi.',
        'blog.post2.title': 'Si Può Friggere con l\'Olio Extra Vergine di Oliva?',
        'blog.post2.excerpt': 'Sfatare i miti sui punti di fumo e cucinare con olio d\'oliva premium.',
        'blog.post3.title': 'La Guida Definitiva alla Dieta Mediterranea',
        'blog.post3.excerpt': 'Come incorporare l\'oro liquido nella tua dieta quotidiana per massimi benefici per la salute.',
        'blog.category.recipes': 'Ricette',
        'blog.category.cooking': 'Consigli di Cucina',
        'blog.category.health': 'Salute',
        'blog.readmore': 'Leggi di Più',
        'blog.back': 'Torna al Blog',
        'blog.share': 'Condividi questo articolo',
        'blog.recent': 'Post Recenti',
        'blog.categories': 'Categorie',
        'contact.hero.title': 'Mettiti in Contatto',
        'contact.hero.subtitle': 'Hai domande sui nostri prodotti o opportunità di partnership? Ci piacerebbe sentirti.',
        'contact.call.title': 'Chiamaci',
        'contact.call.hours': 'Lun-Ven, 9:00 - 18:00 EST',
        'contact.email.title': 'Inviaci un\'Email',
        'contact.visit.title': 'Visitaci',
        'contact.follow': 'Seguici',
        'contact.form.title': 'Invia un Messaggio',
        'contact.form.name': 'Nome Completo',
        'contact.form.email': 'Indirizzo Email',
        'contact.form.subject': 'Oggetto',
        'contact.form.message': 'Messaggio',
        'contact.form.submit': 'Invia Messaggio',
        'contact.form.placeholder.name': 'Mario Rossi',
        'contact.form.placeholder.email': 'mario@example.com',
        'contact.form.placeholder.subject': 'Richiesta Ordine',
        'contact.form.placeholder.message': 'Come possiamo aiutarti?',
        'contact.map.coming': 'Mappa Interattiva in Arrivo',
        'contact.success': 'Grazie per il tuo messaggio! Ti risponderemo presto.',
        'login.title': 'Bentornato',
        'login.email': 'Indirizzo Email',
        'login.password': 'Password',
        'login.submit': 'Accedi',
        'login.no_account': 'Non hai un account?',
        'login.create': 'Creane uno',
        'login.placeholder.email': 'tu@example.com',
        'register.title': 'Crea Account',
        'register.name': 'Nome Completo',
        'register.email': 'Indirizzo Email',
        'register.password': 'Password',
        'register.confirm_password': 'Conferma Password',
        'register.submit': 'Registrati',
        'register.processing': 'Elaborazione...',
        'register.have_account': 'Hai già un account?',
        'register.signin': 'Accedi',
        'register.placeholder.name': 'Mario Rossi',
        'register.placeholder.email': 'tu@example.com',
        'register.error.password_mismatch': 'Le password non corrispondono!',
        'register.error.generic': 'Qualcosa è andato storto',
        'register.error.failed': 'Registrazione Fallita',
        'register.success.otp_sent': 'OTP Inviato a',
        'register.success.registered': 'Registrazione Riuscita!',
        'register.otp.title': 'Verifica Email',
        'register.otp.message': 'Inserisci il codice a 6 cifre inviato a',
        'register.otp.placeholder': 'Inserisci OTP',
        'register.otp.verify': 'Verifica e Accedi',
        'register.otp.verifying': 'Verifica in corso...',
        'register.otp.cancel': 'Annulla',
        'product.breadcrumb.home': 'Home',
        'product.breadcrumb.shop': 'Negozio',
        'product.collection': 'Collezione',
        'product.reviews': 'Basato su 124 recensioni',
        'product.vegan': '100% Vegano',
        'product.eco_packaging': 'Imballaggio Ecologico',
        'product.select_size': 'Seleziona Taglia:',
        'product.add_to_cart': 'Aggiungi al Carrello',
        'product.free_shipping': 'Spedizione gratuita in tutto il mondo',
        'product.warranty': 'Garanzia di 2 Anni',
        'product.tab.description': 'Descrizione',
        'product.tab.nutrition': 'Valori Nutrizionali',
        'product.tab.shipping': 'Spedizione e Resi',
        'product.desc.title': 'Descrizione del Prodotto',
        'product.desc.ingredients': 'Ingredienti:',
        'product.nutrition.title': 'Informazioni Nutrizionali',
        'product.shipping.title': 'Informazioni sulla Spedizione',
        'product.shipping.text': 'Spediamo in tutto il mondo. Ordini elaborati entro 24 ore.',
        'product.shipping.standard': 'Spedizione Standard: 5-7 giorni lavorativi',
        'product.shipping.express': 'Spedizione Express: 2-3 giorni lavorativi',
        'product.related': 'Potrebbe Piacerti Anche',
        'product.not_found': 'Prodotto Non Trovato',
        'product.not_found.desc': 'Il prodotto richiesto non esiste.',
        'admin.dashboard.title': 'Panoramica Dashboard',
        'admin.sales': 'Vendite Totali',
        'admin.orders': 'Ordini Totali',
        'admin.products': 'Prodotti Totali',
        'admin.customers': 'Clienti',
        'admin.low_stock': 'Scorte Basse',
        'admin.recent_orders': 'Ordini Recenti',
        'admin.order_id': 'ID Ordine',
        'admin.customer': 'Cliente',
        'admin.date': 'Data',
        'admin.status': 'Stato',
        'admin.total': 'Totale',
        'admin.no_orders': 'Nessun ordine trovato',
        'admin.products.title': 'Gestione Prodotti',
        'admin.products.add': '+ Aggiungi Nuovo Prodotto',
        'admin.products.id': 'ID',
        'admin.products.name': 'Nome Prodotto',
        'admin.products.category': 'Categoria',
        'admin.products.price': 'Prezzo',
        'admin.products.stock': 'Scorte',
        'admin.products.actions': 'Azioni',
        'admin.products.edit': 'Modifica',
        'admin.products.delete': 'Elimina',
        'admin.products.delete_confirm': 'Sei sicuro di voler eliminare questo prodotto?',
        'admin.orders.title': 'Gestione Ordini',
        'admin.orders.payment': 'Pagamento',
        'admin.orders.view': 'Visualizza',
        'admin.orders.no_orders': 'Nessun ordine trovato.',
        'admin.coupons.title': 'Gestione Coupon',
        'admin.coupons.add': 'Aggiungi Coupon',
        'admin.coupons.form_title': 'Aggiungi Nuovo Coupon',
        'admin.coupons.code': 'Codice Coupon',
        'admin.coupons.code_placeholder': 'ESTATE25',
        'admin.coupons.expiration': 'Data di Scadenza',
        'admin.coupons.discount_type': 'Tipo di Sconto',
        'admin.coupons.discount_value': 'Valore Sconto',
        'admin.coupons.type_percentage': 'Percentuale (%)',
        'admin.coupons.type_fixed': 'Importo Fisso ($)',
        'admin.coupons.create': 'Crea Coupon',
        'admin.coupons.discount': 'Sconto',
        'admin.coupons.expires': 'Scade',
        'admin.coupons.active': 'Attivo',
        'admin.coupons.inactive': 'Inattivo',
        'admin.coupons.delete_title': 'Elimina Coupon',
        'admin.coupons.no_coupons': 'Nessun coupon trovato.',
        'admin.order_view.back': 'Torna agli Ordini',
        'admin.order_view.order': 'Ordine',
        'admin.order_view.placed': 'Effettuato il',
        'admin.order_view.pending': 'In Attesa',
        'admin.order_view.processing': 'In Elaborazione',
        'admin.order_view.shipped': 'Spedito',
        'admin.order_view.completed': 'Completato',
        'admin.order_view.cancelled': 'Annullato',
        'admin.order_view.items': 'Articoli',
        'admin.order_view.product': 'Prodotto',
        'admin.order_view.quantity': 'Quantità',
        'admin.order_view.subtotal': 'Subtotale',
        'admin.order_view.shipping': 'Spedizione',
        'admin.order_view.customer_details': 'Dettagli Cliente',
        'admin.order_view.shipping_address': 'Indirizzo di Spedizione',
        'admin.order_view.no_address': 'Nessun indirizzo fornito',
        'admin.order_view.payment_info': 'Info Pagamento',
        'admin.order_view.paid': 'PAGATO',
        'admin.order_view.not_found': 'Ordine non trovato',
        'admin.add_product.title': 'Aggiungi Nuovo Prodotto',
        'admin.add_product.name': 'Nome Prodotto',
        'admin.add_product.name_placeholder': 'es. Olio di Basilico Biologico',
        'admin.add_product.price': 'Prezzo ($)',
        'admin.add_product.stock': 'Quantità in Magazzino',
        'admin.add_product.image': 'Immagine Prodotto',
        'admin.add_product.image_url': 'URL Immagine',
        'admin.add_product.upload_file': 'Carica File',
        'admin.add_product.url_placeholder': 'https://example.com/immagine.jpg',
        'admin.add_product.gallery': 'Immagini Galleria (Opzionale)',
        'admin.add_product.description': 'Descrizione',
        'admin.add_product.desc_placeholder': 'Descrizione del prodotto...',
        'admin.add_product.cancel': 'Annulla',
        'admin.add_product.save': 'Salva Prodotto',
        'admin.add_product.success': 'Prodotto Aggiunto con Successo!',
        'admin.add_product.error_image': 'Seleziona un file immagine.',
        'admin.add_product.error_url': 'Inserisci un URL immagine.',
        'admin.add_product.error_file': 'Impossibile leggere il file immagine.',
        'admin.edit_product.title': 'Modifica Prodotto',
        'admin.edit_product.update': 'Aggiorna Prodotto',
        'admin.edit_product.success': 'Prodotto Aggiornato con Successo!',
        'admin.edit_product.not_found': 'Prodotto non trovato',
        'admin.edit_product.loading': 'Caricamento...',
        'admin.edit_product.gallery_label': 'Immagini Galleria',
        'tracking.title': 'Tracciamento Ordine',
        'tracking.not_found': 'Ordine non trovato',
        'tracking.not_found_desc': 'Impossibile trovare le informazioni di tracciamento per ID:',
        'tracking.step.placed': 'Ordine Effettuato',
        'tracking.step.processing': 'In Elaborazione',
        'tracking.step.shipped': 'Spedito',
        'tracking.step.delivered': 'Consegnato',
        'tracking.time.in_progress': 'In Corso',
        'tracking.time.estimated_2days': 'Stimato 2 Giorni',
        'tracking.time.estimated_5days': 'Stimato 5 Giorni',
        'tracking.details': 'Dettagli Tracciamento',
        'tracking.package_status': 'Il tuo pacco è attualmente',
        'tracking.shipped_msg': 'È in viaggio verso il centro di consegna.',
        'tracking.processing_msg': 'Stiamo imballando i tuoi articoli con cura.',
        'tracking.id': 'ID Tracciamento',
        'tracking.carrier': 'Corriere',
        'admin.nav.dashboard': 'Dashboard',
        'admin.nav.products': 'Prodotti',
        'admin.nav.orders': 'Ordini',
        'admin.nav.coupons': 'Coupon',
        'admin.nav.back_to_store': 'Torna al Negozio',
        'admin.nav.logout': 'Esci',
        'dashboard': 'Dashboard',
        'products': 'Prodotti',
        'orders': 'Ordini',
        'coupons': 'Coupon',
        'back_to_store': 'Torna al Negozio',
        'logout': 'Esci',
    },
    pt: {
        'nav.home': 'Início', 'nav.products': 'Produtos', 'nav.about': 'Sobre', 'nav.contact': 'Contato',
        'nav.login': 'Entrar', 'nav.logout': 'Sair',
        'hero.title': 'Óleo Olive Premium', 'hero.subtitle': 'Experimente a pureza da natureza com nosso azeite de oliva prensado a frio.', 'hero.cta': 'Comprar agora',
        'footer.text': '© 2026 Green Gold. Todos os direitos reservados.',
        'cart.title': 'Seu Carrinho', 'cart.checkout': 'Ir para o pagamento', 'common.loading': 'Carregando...',
        'home.hero.title': 'Ouro Puro da Natureza',
        'home.hero.subtitle': 'Experimente a riqueza do Green Gold (Azeite de Oliva) premium prensado a frio. Origem global, entrega local.',
        'home.why': 'Por que escolher Green Gold?',
        'home.featured': 'Coleções em Destaque',
        'home.about.title': 'A Essência da Pureza',
        'home.testimonials': 'O que nossos clientes dizem',
    },
    zh: {
        'nav.home': '首页', 'nav.products': '产品', 'nav.about': '关于我们', 'nav.contact': '联系方式',
        'nav.login': '登录', 'nav.logout': '登出',
        'hero.title': '优质 Olive 油', 'hero.subtitle': '体验我们冷榨橄榄油的自然纯净。', 'hero.cta': '立即购买',
        'footer.text': '© 2026 Green Gold. 保留所有权利。',
        'cart.title': '您的购物车', 'cart.checkout': '去结账', 'common.loading': '加载中...',
        'home.hero.title': '来自自然的纯金',
        'home.hero.subtitle': '体验优质冷榨绿金（橄榄油）的丰富口感。全球采购，本地交付。',
        'home.why': '为何选择绿金？',
        'home.featured': '精选系列',
        'home.about.title': '纯净的本质',
        'home.testimonials': '客户评价',
    },
    ja: {
        'nav.home': 'ホーム', 'nav.products': '製品', 'nav.about': '約', 'nav.contact': '連絡先',
        'nav.login': 'ログイン', 'nav.logout': 'ログアウト',
        'hero.title': 'プレミアム Olive オイル', 'hero.subtitle': 'コールドプレスオリーブオイルで自然の純粋さを体験してください。', 'hero.cta': '今すぐ購入',
        'footer.text': '© 2026 Green Gold. 全著作権所有。',
        'cart.title': 'ショッピングカート', 'cart.checkout': 'チェックアウトへ進む', 'common.loading': '読み込み中...',
        'home.hero.title': '自然からの純金',
        'home.hero.subtitle': 'プレミアムなコールドプレス・グリーンゴールド（オリーブオイル）の豊かさを体験してください。',
        'home.why': 'なぜグリーンゴールドを選ぶのか？',
        'home.featured': '注目コレクション',
        'home.about.title': '純粋さの本質',
        'home.testimonials': 'お客様の声',
    },
    ru: {
        'nav.home': 'Главная', 'nav.products': 'Продукты', 'nav.about': 'О нас', 'nav.contact': 'Контакты',
        'nav.login': 'Войти', 'nav.logout': 'Выйти',
        'hero.title': 'Премиум Масло Jaitun', 'hero.subtitle': 'Почувствуйте чистоту природы с нашим оливковым маслом холодного отжима.', 'hero.cta': 'Купить сейчас',
        'footer.text': '© 2026 Green Gold. Все права защищены.',
        'cart.title': 'Ваша корзина', 'cart.checkout': 'Оформить заказ', 'common.loading': 'Загрузка...',
        'home.hero.title': 'Чистое Золото Природы',
        'home.hero.subtitle': 'Почувствуйте богатство премиального оливкового масла холодного отжима Green Gold.',
        'home.why': 'Почему выбирают Green Gold?',
        'home.featured': 'Избранные Коллекции',
        'home.about.title': 'Сущность Чистоты',
        'home.testimonials': 'Отзывы наших клиентов',
    },
    ar: {
        'nav.home': 'الرئيسية', 'nav.products': 'المنتجات', 'nav.about': 'عن', 'nav.contact': 'اتصل',
        'nav.login': 'تسجيل الدخول', 'nav.logout': 'تسجيل الخروج',
        'hero.title': 'زيت زيتون فاخر', 'hero.subtitle': 'جرب نقاء الطبيعة مع زيت الزيتون المعصور على البارد.', 'hero.cta': 'تسوق الآن',
        'footer.text': '© 2026 Green Gold. جميع الحقوق محفوظة.',
        'cart.title': 'عربة التسوق الخاصة بك', 'cart.checkout': 'الدفع', 'common.loading': 'جار التحميل...',
        'home.hero.title': 'ذهب خالص من الطبيعة',
        'home.hero.subtitle': 'جرب ثراء الذهب الأخضر (زيت الزيتون) الممتاز المعصور على البارد.',
        'home.why': 'لماذا تختار الذهب الأخضر؟',
        'home.featured': 'مجموعات مميزة',
        'home.about.title': 'جوهر النقاء',
        'home.testimonials': 'ماذا يقول عملاؤنا',
    }
};

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
    const [language, setLanguage] = useState<Language>('en');

    // Persist language preference
    useEffect(() => {
        const savedLang = localStorage.getItem('jaitun_lang') as Language;
        if (savedLang && ['en', 'hi', 'es', 'fr', 'de', 'it', 'pt', 'zh', 'ja', 'ru', 'ar'].includes(savedLang)) {
            // eslint-disable-next-line react-hooks/set-state-in-effect
            setLanguage(savedLang);
        }
    }, []);

    const changeLanguage = (lang: Language) => {
        setLanguage(lang);
        localStorage.setItem('jaitun_lang', lang);
    };

    const t = (key: string): string => {
        return translations[language][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage: changeLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};
